import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import ToastifyWrapper from "../context/ToastifyWrapper";
import QueryWrapper from "@/context/QueryWrapper";

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Chat Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <QueryWrapper>
        <body
          className={`${poppins.className} w-full min-h-screen flex justify-center items-center`}
        >
          <ToastifyWrapper>{children}</ToastifyWrapper>
        </body>
      </QueryWrapper>
    </html>
  );
}
