import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import ToastifyWrapper from "../context/ToastifyWrapper";
import QueryWrapper from "@/context/QueryWrapper";
import Navbar from "@/components/Navbar/Navbar";
import LayoutWrapper from "@/layout/LayoutWrapper";

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Chat Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <QueryWrapper>
        <body
          className={`${poppins.className} flex min-h-screen w-full items-center justify-center bg-[#f8f8f8]`}
        >
          <ToastifyWrapper>
            <LayoutWrapper className="flex-col-reverse border-2 border-[#ffffff] bg-background sm:flex-row sm:p-2">
              <Navbar />
              {children}
            </LayoutWrapper>
          </ToastifyWrapper>
        </body>
      </QueryWrapper>
    </html>
  );
}
